/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

/**
 *
 * @author PC
 */
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.sql.Timestamp;
import javax.swing.JFrame;
public class managedrink extends javax.swing.JFrame {

    /**
     * Creates new form managedrink
     */
    public managedrink() {
        initComponents();
        ShowProducts();
    }
    int PrNum;
    private void CountProd(){
        try {
            Connection Con1 = JDBC_Connection.getConnection();
            Statement st1 = Con1.createStatement();
            ResultSet rs1 = st1.executeQuery("select Max(PNum) form product");
            rs1.next();
            PrNum = rs1.getInt(1) + 1;
        } catch (Exception e) {
            
        }
    }
    private void ShowProducts(){
        try{
            Connection Con = JDBC_Connection.getConnection();
            Statement ps = Con.createStatement();
            ResultSet rs = ps.executeQuery("SELECT * FROM management_cafe.product");
            Product_List.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewbill = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        signout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        status_tf = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        insert_bt = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        description_tf = new javax.swing.JTextField();
        price_tf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        search_bt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        image_tf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        quantity_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Product_List = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 77, 26));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGE DRINK");

        viewbill.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewbill.setForeground(new java.awt.Color(255, 255, 255));
        viewbill.setText("VIEW BILL");
        viewbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbillMouseClicked(evt);
            }
        });

        report.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("REPORT");
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });

        signout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setText("SIGN OUT");
        signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MANAGE EMPLOYEE");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(signout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewbill)
                            .addComponent(jLabel2)
                            .addComponent(report)
                            .addComponent(jLabel3))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(114, 114, 114)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(viewbill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(report)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(signout)
                .addGap(70, 70, 70))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 570));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(129, 77, 26));
        jLabel7.setText("Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 40, -1));

        name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_tfActionPerformed(evt);
            }
        });
        jPanel3.add(name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 108, -1));

        status_tf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "active", "inactive" }));
        status_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_tfActionPerformed(evt);
            }
        });
        jPanel3.add(status_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(129, 77, 26));
        jLabel10.setText("Status");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        insert_bt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        insert_bt.setForeground(new java.awt.Color(129, 77, 26));
        insert_bt.setText("INSERT");
        insert_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btActionPerformed(evt);
            }
        });
        jPanel3.add(insert_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(129, 77, 26));
        jLabel11.setText("Description");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));
        jPanel3.add(description_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 110, -1));
        jPanel3.add(price_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 120, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(129, 77, 26));
        jLabel8.setText("Price");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));

        search_bt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search_bt.setForeground(new java.awt.Color(129, 77, 26));
        search_bt.setText("SEARCH");
        search_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btActionPerformed(evt);
            }
        });
        jPanel3.add(search_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(129, 77, 26));
        jLabel12.setText("Image");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, 20));

        image_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_tfActionPerformed(evt);
            }
        });
        jPanel3.add(image_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(129, 77, 26));
        jLabel9.setText("Quantity");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));
        jPanel3.add(quantity_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 107, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(129, 77, 26));
        jLabel6.setText("MANAGE DRINK");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        Product_List.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "PRICE", "QUANTITY", "CREATED_DATE", "UPDATED_DATE", "STATUS", "DESCRIPTION", "IMAGE"
            }
        ));
        jScrollPane1.setViewportView(Product_List);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 580, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean isInteger(String input) {
    try {
        Integer.parseInt(input);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}
    private void name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_tfActionPerformed

    private void insert_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btActionPerformed
        PreparedStatement ps;
        if (name_tf.getText().isEmpty() || price_tf.getText().isEmpty() || quantity_tf.getText().isEmpty() || status_tf.getSelectedIndex()== -1 || description_tf.getText().isEmpty() || image_tf.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }else if (!isInteger(price_tf.getText()) || !isInteger(quantity_tf.getText())) {
    JOptionPane.showMessageDialog(this, "Wrong Format!");
}

            else{
            try {
                CountProd();
                Connection Con = JDBC_Connection.getConnection();
                ps = Con.prepareStatement("insert into product values(?,?,?,?,?,?,?,?,?)");
                ps.setInt(1, PrNum);
                ps.setString(2, name_tf.getText());
                ps.setInt(3, Integer.parseInt(price_tf.getText()));
                ps.setInt(4, Integer.parseInt(quantity_tf.getText()));
                ps.setTimestamp(5, new Timestamp(System.currentTimeMillis()));
                ps.setTimestamp(6, new Timestamp(System.currentTimeMillis()));
                ps.setString(7, status_tf.getSelectedItem().toString());
                ps.setString(8, description_tf.getText());
                ps.setString(9, image_tf.getText());
                int row = ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Add successfully!");
                Con.close();
                ShowProducts();
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_insert_btActionPerformed

    private void search_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btActionPerformed

        searchdrink searchdr = new searchdrink();
        searchdr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        searchdr.setVisible(true);
    }//GEN-LAST:event_search_btActionPerformed

    private void signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseClicked
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signoutMouseClicked

    private void viewbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbillMouseClicked
        new Viewbill().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewbillMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportMouseClicked

    private void status_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_tfActionPerformed

    private void image_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_image_tfActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new manageemployee().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managedrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managedrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managedrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managedrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managedrink().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Product_List;
    private javax.swing.JTextField description_tf;
    private javax.swing.JTextField image_tf;
    private javax.swing.JButton insert_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name_tf;
    private javax.swing.JTextField price_tf;
    private javax.swing.JTextField quantity_tf;
    private javax.swing.JLabel report;
    private javax.swing.JButton search_bt;
    private javax.swing.JLabel signout;
    private javax.swing.JComboBox<String> status_tf;
    private javax.swing.JLabel viewbill;
    // End of variables declaration//GEN-END:variables
}
